---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-penpot-tryb-co-za
  namespace: penpot
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "le-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    certmanager.k8s.io/acme-challenge-type: http01
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"

    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - penpot.toolbox.tryb.co.za

    secretName: tls-penpot-tryb
  rules:
  - host: penpot.toolbox.tryb.co.za

    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: penpot-frontend
            port: 
              number: 80
