apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: penpot-postgres
  name: penpot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: penpot-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/penpot: "true"
        io.kompose.service: penpot-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: penpot
            - name: POSTGRES_INITDB_ARGS
              value: --data-checksums
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PENPOT_DATABASE_PASSWORD
                  name: docker-compose-penpot-env

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: PENPOT_DATABASE_USERNAME
                  name: docker-compose-penpot-env

          image: postgres:13
          name: penpot-postgres
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: penpot-postgres-data
      restartPolicy: Always
      volumes:
        - name: penpot-postgres-data
          persistentVolumeClaim:
            claimName: penpot-postgres-data
status: {}
